### ISSUE TITLE
Test Case Failed on dev branch

### ISSUE THREAD

**Issue by BitVivek** [BitVivek/COMP367_Groupproject#5]
postLogin - Failed Test Case:

Issue: Missing fields (email, password, or type) are not handled correctly; the message in the rendered data is undefined.
Cause: alertMessage.alertMessage return value is not assigned to message.

postRegister - Failed Test Case:

Issue: Missing fields (email, password, or name) result in undefined message in the rendered data.
Cause: alertMessage.alertMessage return value is not assigned to message.

**Comment by BitVivek** [comment]
@AneesaZaki https://github.com/BitVivek/COMP367_Groupproject/pull/6

**Comment by BitVivek** [comment]
I have created PR , please review and merge

**Comment by AneesaZaki** [comment]
Resolved
